import fs from 'fs';
import path from 'path';

// Live site metrics rolled up from Ascend state (agents, tests, trust, value
// saved). Generated by Ascend's scripts/site_metrics_rollup.py and committed to
// data/site/metrics.json. See docs/redesign/02_DATA_MODEL_AND_GAPS.md §5.

export interface HeroMetric {
  label: string;
  value: string;
  sub: string;
}

export interface SiteMetrics {
  generated_at: string;
  availability: { open: boolean; label: string };
  hero_metrics: HeroMetric[];
  category_counts: Record<string, number>;
  system_status: string;
}

const METRICS_PATH = path.join(process.cwd(), 'data/site/metrics.json');

const FALLBACK: SiteMetrics = {
  generated_at: '',
  availability: { open: true, label: 'AVAILABLE FOR NEW ENGAGEMENTS' },
  hero_metrics: [
    { label: 'AGENTS', value: '30', sub: '20 mature' },
    { label: 'TESTS', value: '1,375', sub: 'ruff+mypy clean' },
    { label: 'TRUST', value: 'L0–L4', sub: 'auto-gated' },
    { label: 'AUTOMATED', value: '120h+', sub: 'saved to date' },
  ],
  category_counts: {
    architecture: 0,
    infrastructure: 0,
    optimization: 0,
    research: 0,
  },
  system_status: 'ONLINE',
};

export function getSiteMetrics(): SiteMetrics {
  try {
    const raw = fs.readFileSync(METRICS_PATH, 'utf8');
    return JSON.parse(raw) as SiteMetrics;
  } catch {
    return FALLBACK;
  }
}
